sonar.projectKey=kavyamguru_MSc_Dissertation_Kvass
sonar.organization=kavyamguru
sonar.projectName=MSc_Dissertation_Kvass
sonar.host.url=https://sonarcloud.io

# Source settings
sonar.sources=code
sonar.sourceEncoding=UTF-8

# Keep scans limited to code only (avoid raw data/results)
sonar.exclusions=metadata/**,raw_data_links/**,results/**,**/*.pdf,**/*.txt
